---
env: 'test'

maci:
  initialVoiceCreditBalance: 100
  signUpDurationInSeconds: 3600 # 1 hour
  votingDurationInSeconds: 3600 # 1 hour
  coordinatorPrivKey: "2222222222263902553431241761119057960280734584214105336279476766401963593688"
  messageBatchSize: 4
  quadVoteTallyBatchSize: 4
  voteOptionsMaxLeafIndex: 3

  merkleTrees:
    stateTreeDepth: 4
    messageTreeDepth: 4
    voteOptionTreeDepth: 2

chain:
  privateKeysPath: './'
  testMnemonic: "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
  url: "http://localhost:8545"
  ganache:
    port: 8545

zkutil_bin: "~/.cargo/bin/zkutil"
